name: Ejecutar Notificador de HackerOne

on:
  schedule:
    - cron: "0 */3 * * *"  # Cada 3 horas
  workflow_dispatch:  # Ejecución manual

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Clonar el repositorio
        uses: actions/checkout@v4

      - name: 📂 Intentar descargar último estado (si existe)
        continue-on-error: true  # Evita que falle si no existe aún
        uses: actions/download-artifact@v4
        with:
          name: latest-program
          path: .

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # 3.13 aún no es estable en todos los runners

      - name: 📦 Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: 🚀 Ejecutar script de monitoreo
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python notifier.py

      - name: 📤 Subir estado actualizado
        uses: actions/upload-artifact@v4
        with:
          name: latest-program
          path: latest_program.json
