name: Ejecutar Notificador de HackerOne

on:
  schedule:
    - cron: "0 */3 * * *"  # Cada 3 horas
  workflow_dispatch:  # Ejecución manual

permissions:
  contents: write  # 🔐 Permite push a mi repo

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Clonar el repositorio
        uses: actions/checkout@v4

      - name: 🐍 Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: 🚀 Ejecutar script de monitoreo
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }} #Claro, variables de entorno, que dijo navidad? v: 
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python notifier.py

      - name: 🔄 Commit y push de latest_program.json al repositorio #Con esto me ahorro el bug que tenía con Artifacts en github actions, más persistente asi. 
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add latest_program.json
          git diff --cached --quiet || git commit -m "chore: update latest_program.json with new HackerOne program state"
          git push
